version: "2"

volumes:
  kafka_data:
    driver: local

networks:
  default_net:
    driver: bridge

services:
    kafka:
      image: docker.io/bitnami/kafka:3.4.0-debian-11-r23
      networks:
        - default_net
      ports:
        - "9094:9094"
      volumes:
        - "kafka_data:/bitnami"
      environment:
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_KRAFT_CLUSTER_ID=9YoavaRpTCOitT3Dm2OQFQ
        - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9094
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT

    kafka-ui:
      image: provectuslabs/kafka-ui:v0.7.0
      networks:
        - default_net
      ports:
        - "9000:8080"
      depends_on:
        kafka:
          condition: service_started
      environment:
        KAFKA_CLUSTERS_0_NAME: lineage
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
        DYNAMIC_CONFIG_ENABLED: 'true'

    neo4j:
      container_name: neo4j
      image: neo4j:latest
      networks:
        - default_net
      ports:
        - 7474:7474
        - 7687:7687
      environment:
        - NEO4J_AUTH=neo4j/password
        - NEO4J_apoc_export_file_enabled=true
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_apoc_import_file_use__neo4j__config=true
        - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      volumes:
        - ./neo4j_db/data:/data
        - ./neo4j_db/logs:/logs
        - ./neo4j_db/import:/var/lib/neo4j/import
        - ./neo4j_db/plugins:/plugins